# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    environment:
      name: publish
      url: https://pypi.org/p/libreserver
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Install Package
      run: |
        python -m pip install virtualenv
        make devenv
    - name: Check styles
      run: |
        make check
    - name: Install Libreoffice
      run: |
        sudo apt-get update
        sudo apt-get install libreoffice
    - name: Test with pytest
      run: |
        source ve/bin/activate
        make test
    - name: Build package
      run: |
        make build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
